apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-consumer
  name: spring-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-consumer
  template:
    metadata:
      labels:
        app: spring-consumer
    spec:
      containers:
        - name: spring-consumer
          image: davidmachacek/kafka-consumer:latest
          imagePullPolicy: Always
          env:
            - name: BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap:9093
            - name: TOPIC
              value: my-topic-replicated
            - name: CA_CRT
              valueFrom:
                secretKeyRef:
                  name: kafka-cluster-cluster-ca-cert
                  key: ca.crt
            - name: USER_CRT
              valueFrom:
                secretKeyRef:
                  name: my-user
                  key: user.crt
            - name: USER_KEY
              valueFrom:
                secretKeyRef:
                  name: my-user
                  key: user.key
            - name: GROUP_ID
              value: my-group
            - name: LOG_LEVEL
              value: "INFO"
            - name: MESSAGE_COUNT
              value: "1000000"
            - name: PRODUCER_ACKS
              value: "all"
            - name: ADDITIONAL_CONFIG
              value: |
                max.poll.records=100